#!/bin/bash
set -e

# ==============================================================================
# Haven Start9 Entrypoint Script
# ==============================================================================

# Color codes for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_debug() {
    echo -e "${CYAN}[DEBUG]${NC} $1"
}

# ==============================================================================
# Signal Handling for Graceful Shutdown
# ==============================================================================

cleanup() {
    log_info "Received shutdown signal, cleaning up..."
    
    # Kill Haven process gracefully
    if [ ! -z "$HAVEN_PID" ] && kill -0 $HAVEN_PID 2>/dev/null; then
        log_info "Stopping Haven..."
        kill -TERM $HAVEN_PID
        wait $HAVEN_PID 2>/dev/null || true
    fi
    
    # Kill Tor process
    if [ ! -z "$TOR_PID" ] && kill -0 $TOR_PID 2>/dev/null; then
        log_info "Stopping Tor..."
        kill -TERM $TOR_PID
        wait $TOR_PID 2>/dev/null || true
    fi
    
    log_info "Shutdown complete"
    exit 0
}

trap cleanup SIGTERM SIGINT SIGQUIT

# ==============================================================================
# Environment File Generation
# ==============================================================================

generate_env_file() {
    log_info "Generating Haven configuration from Start9 environment..."
    
    cat > /app/.env <<EOF
# ==============================================================================
# Haven Configuration (Generated by Start9)
# ==============================================================================

# Owner Configuration
OWNER_NPUB=${OWNER_NPUB}

# Database Configuration
DB_ENGINE=${DB_ENGINE:-badger}

# Blossom Storage
BLOSSOM_PATH=/data/blossom/

# Relay Configuration
RELAY_URL=${TOR_ADDRESS}
RELAY_PORT=3355
RELAY_BIND_ADDRESS=0.0.0.0
RELAY_VERSION=${RELAY_VERSION:-1.0.8}

# Private Relay Configuration
PRIVATE_RELAY_NAME=${PRIVATE_RELAY_NAME:-Haven Private}
PRIVATE_RELAY_NPUB=${OWNER_NPUB}
PRIVATE_RELAY_DESCRIPTION=${PRIVATE_RELAY_DESCRIPTION:-My private relay}
PRIVATE_RELAY_ICON=${PRIVATE_RELAY_ICON:-}

# Chat Relay Configuration
CHAT_RELAY_NAME=${CHAT_RELAY_NAME:-Haven Chat}
CHAT_RELAY_NPUB=${OWNER_NPUB}
CHAT_RELAY_DESCRIPTION=${CHAT_RELAY_DESCRIPTION:-My chat relay}
CHAT_RELAY_ICON=${CHAT_RELAY_ICON:-}
CHAT_RELAY_WOT_DEPTH=${CHAT_RELAY_WOT_DEPTH:-2}
CHAT_RELAY_WOT_REFRESH_INTERVAL_HOURS=${CHAT_RELAY_WOT_REFRESH_INTERVAL_HOURS:-24}
CHAT_RELAY_MINIMUM_FOLLOWERS=${CHAT_RELAY_MINIMUM_FOLLOWERS:-10}

# Outbox Relay Configuration
OUTBOX_RELAY_NAME=${OUTBOX_RELAY_NAME:-Haven Outbox}
OUTBOX_RELAY_NPUB=${OWNER_NPUB}
OUTBOX_RELAY_DESCRIPTION=${OUTBOX_RELAY_DESCRIPTION:-My outbox relay}
OUTBOX_RELAY_ICON=${OUTBOX_RELAY_ICON:-}

# Inbox Relay Configuration
INBOX_RELAY_NAME=${INBOX_RELAY_NAME:-Haven Inbox}
INBOX_RELAY_NPUB=${OWNER_NPUB}
INBOX_RELAY_DESCRIPTION=${INBOX_RELAY_DESCRIPTION:-My inbox relay}
INBOX_RELAY_ICON=${INBOX_RELAY_ICON:-}
INBOX_PULL_INTERVAL_SECONDS=${INBOX_PULL_INTERVAL_SECONDS:-3600}

# Import Settings
IMPORT_START_DATE=${IMPORT_START_DATE:-}
IMPORT_OWNER_NOTES_FETCH_TIMEOUT_SECONDS=30
IMPORT_TAGGED_NOTES_FETCH_TIMEOUT_SECONDS=120
IMPORT_QUERY_INTERVAL_SECONDS=360000
IMPORT_SEED_RELAYS_FILE=/app/relays_import.json
BLASTR_RELAYS_FILE=/app/relays_blastr.json

# Backup Configuration
BACKUP_PROVIDER=${BACKUP_PROVIDER:-none}
BACKUP_INTERVAL_HOURS=${BACKUP_INTERVAL_HOURS:-24}

# Advanced Settings
WOT_FETCH_TIMEOUT_SECONDS=30
HAVEN_LOG_LEVEL=${LOG_LEVEL:-INFO}
EOF

    log_info "Configuration file generated successfully"
}

# ==============================================================================
# Configuration Validation
# ==============================================================================

validate_config() {
    log_info "Validating configuration..."
    
    if [ -z "$OWNER_NPUB" ]; then
        log_error "OWNER_NPUB is not set. Please configure your Nostr public key."
        exit 1
    fi
    
    # Validate npub format (starts with npub1)
    if [[ ! "$OWNER_NPUB" =~ ^npub1[a-z0-9]{58}$ ]]; then
        log_error "Invalid OWNER_NPUB format. Must start with 'npub1' and be 63 characters long."
        exit 1
    fi
    
    log_info "Configuration validated successfully"
}

# ==============================================================================
# Relay List Initialization
# ==============================================================================

initialize_relay_lists() {
    log_info "Initializing relay lists..."
    
    # Create empty relay list files in /app as haven user
    # Haven will populate these files during operation
    if [ ! -f /app/relays_import.json ]; then
        log_info "Creating empty import relay list in /app..."
        su-exec haven sh -c 'echo "[]" > /app/relays_import.json'
    else
        log_info "Import relay list already exists"
    fi
    
    if [ ! -f /app/relays_blastr.json ]; then
        log_info "Creating empty blastr relay list in /app..."
        su-exec haven sh -c 'echo "[]" > /app/relays_blastr.json'
    else
        log_info "Blastr relay list already exists"
    fi
    
    log_info "Relay lists initialized"
}

# ==============================================================================
# Tor Hidden Service Setup
# ==============================================================================

start_tor() {
    log_info "Starting Tor Hidden Service..."
    
    # Ensure /data/tor/haven directory exists with correct permissions
    if [ ! -d /data/tor/haven ]; then
        log_info "Creating Tor data directory at /data/tor/haven..."
        mkdir -p /data/tor/haven
        chown -R haven:haven /data/tor
        chmod 700 /data/tor/haven
    fi
    
    # Check if this is a first-time setup or restore
    if [ -f /data/tor/haven/hostname ]; then
        log_info "Existing .onion address found (will reuse)"
    else
        log_info "No existing .onion address found (will generate new one)"
    fi
    
    # Start Tor in background as haven user
    su-exec haven tor -f /etc/tor/torrc &
    TOR_PID=$!
    
    # Wait for Tor to generate/load .onion address (max 30 seconds)
    TIMEOUT=30
    ELAPSED=0
    while [ ! -f /data/tor/haven/hostname ] && [ $ELAPSED -lt $TIMEOUT ]; do
        log_debug "Waiting for Tor to generate .onion address... ($ELAPSED/$TIMEOUT seconds)"
        sleep 2
        ELAPSED=$((ELAPSED + 2))
    done
    
    if [ ! -f /data/tor/haven/hostname ]; then
        log_error "Tor failed to generate .onion address within $TIMEOUT seconds"
        exit 1
    fi
    
    # Read and export Tor address
    export TOR_ADDRESS=$(cat /data/tor/haven/hostname)
    log_info "Tor Hidden Service started"
    log_info "Your .onion address: ${GREEN}${TOR_ADDRESS}${NC}"
    
    # Try to write TOR address to file for properties script (optional)
    if echo "$TOR_ADDRESS" > /data/tor_address.txt 2>/dev/null; then
        log_info "Saved Tor address to /data/tor_address.txt"
    else
        log_warn "Could not write /data/tor_address.txt (will use environment variable instead)"
    fi
}

# ==============================================================================
# Haven Application Startup
# ==============================================================================

start_haven() {
    log_info "Starting Haven relay server..."
    
    # Check if this is an import run
    if [ "$RUN_IMPORT" = "true" ]; then
        log_info "Running in import mode..."
        su-exec haven /app/haven --import
        EXIT_CODE=$?
        log_info "Import completed with exit code: $EXIT_CODE"
        exit $EXIT_CODE
    fi
    
    # Start Haven in background as haven user
    su-exec haven /app/haven &
    HAVEN_PID=$!
    
    log_info "Haven started with PID: $HAVEN_PID"
    log_info ""
    log_info "=========================================="
    log_info "  🚀 Haven is now running!"
    log_info "=========================================="
    log_info ""
    log_info "Relay URLs:"
    log_info "  Outbox:  ${CYAN}ws://${TOR_ADDRESS}${NC}"
    log_info "  Private: ${CYAN}ws://${TOR_ADDRESS}/private${NC}"
    log_info "  Chat:    ${CYAN}ws://${TOR_ADDRESS}/chat${NC}"
    log_info "  Inbox:   ${CYAN}ws://${TOR_ADDRESS}/inbox${NC}"
    log_info ""
    log_info "Blossom Server:"
    log_info "  URL:     ${CYAN}http://${TOR_ADDRESS}${NC}"
    log_info ""
    log_info "=========================================="
    log_info ""
    
    # Wait for Haven process
    wait $HAVEN_PID
    EXIT_CODE=$?
    
    log_info "Haven stopped with exit code: $EXIT_CODE"
    return $EXIT_CODE
}

# ==============================================================================
# Main Execution
# ==============================================================================

main() {
    log_info "=========================================="
    log_info "  Haven for Start9 Server"
    log_info "  Version: ${RELAY_VERSION:-1.0.8}"
    log_info "=========================================="
    log_info ""
    
    # Setup /data directory permissions for haven user
    log_info "Setting up data directory permissions..."
    
    # Ensure /data is writable by haven user
    chown -R haven:haven /data 2>/dev/null || log_warn "Could not change /data ownership (may be restricted by Start9)"
    
    # Try to create subdirectories as root, then change ownership
    for dir in db blossom backups start9 tor; do
        if [ ! -d "/data/$dir" ]; then
            mkdir -p "/data/$dir" 2>/dev/null && chown haven:haven "/data/$dir" 2>/dev/null || log_info "Directory /data/$dir will be created by Haven if needed"
        fi
    done
    
    # Load configuration from Start9 (standard location)
    if [ -f /data/start9/config.yaml ]; then
        log_info "Loading configuration from Start9..."
        
        # Extract configuration values using yq
        export OWNER_NPUB=$(yq e '.owner-npub' /data/start9/config.yaml)
        export DB_ENGINE=$(yq e '.db-engine // "badger"' /data/start9/config.yaml)
        export LMDB_MAPSIZE=$(yq e '.lmdb-mapsize // ""' /data/start9/config.yaml)
        export RELAY_VERSION=$(yq e '.relay-version // "1.0.8"' /data/start9/config.yaml)
        
        export PRIVATE_RELAY_NAME=$(yq e '.private-relay-name // "Haven Private"' /data/start9/config.yaml)
        export PRIVATE_RELAY_DESCRIPTION=$(yq e '.private-relay-description // "My private relay"' /data/start9/config.yaml)
        
        export CHAT_RELAY_NAME=$(yq e '.chat-relay-name // "Haven Chat"' /data/start9/config.yaml)
        export CHAT_RELAY_DESCRIPTION=$(yq e '.chat-relay-description // "My chat relay"' /data/start9/config.yaml)
        export CHAT_RELAY_WOT_DEPTH=$(yq e '.chat-wot-depth // "2"' /data/start9/config.yaml)
        export CHAT_RELAY_WOT_REFRESH_INTERVAL_HOURS=$(yq e '.chat-wot-refresh-interval // "24"' /data/start9/config.yaml)
        export CHAT_RELAY_MINIMUM_FOLLOWERS=$(yq e '.chat-minimum-followers // "10"' /data/start9/config.yaml)
        
        export OUTBOX_RELAY_NAME=$(yq e '.outbox-relay-name // "Haven Outbox"' /data/start9/config.yaml)
        export OUTBOX_RELAY_DESCRIPTION=$(yq e '.outbox-relay-description // "My outbox relay"' /data/start9/config.yaml)
        
        export INBOX_RELAY_NAME=$(yq e '.inbox-relay-name // "Haven Inbox"' /data/start9/config.yaml)
        export INBOX_RELAY_DESCRIPTION=$(yq e '.inbox-relay-description // "My inbox relay"' /data/start9/config.yaml)
        export INBOX_PULL_INTERVAL_SECONDS=$(yq e '.inbox-pull-interval // "3600"' /data/start9/config.yaml)
        
        export IMPORT_START_DATE=$(yq e '.import-start-date // ""' /data/start9/config.yaml)
        export BACKUP_PROVIDER=$(yq e '.backup-provider // "none"' /data/start9/config.yaml)
        export BACKUP_INTERVAL_HOURS=$(yq e '.backup-interval // "24"' /data/start9/config.yaml)
        export LOG_LEVEL=$(yq e '.log-level // "INFO"' /data/start9/config.yaml)
        
        log_info "Configuration loaded successfully"
    else
        log_warn "Start9 configuration file not found at /data/start9/config.yaml"
        log_warn "Using default values and environment variables"
    fi
    
    # Run initialization steps
    validate_config
    initialize_relay_lists
    
    # Start Tor (must start before generating .env since TOR_ADDRESS is needed)
    start_tor
    
    # Generate configuration after TOR_ADDRESS is available
    generate_env_file
    
    # Start Haven application
    start_haven
    
    # Exit with Haven's exit code
    exit $?
}

# Run main function
main

