#!/bin/bash

# ==============================================================================
# Haven Configuration Set Script
# Applies new configuration from Start9 UI
# ==============================================================================

set -e

# Read new config from stdin
CONFIG=$(cat)

# Validate required fields
OWNER_NPUB=$(echo "$CONFIG" | yq '.owner-npub')

if [ -z "$OWNER_NPUB" ] || [ "$OWNER_NPUB" = "null" ]; then
    echo "Error: owner-npub is required" >&2
    exit 1
fi

# Validate npub format
if [[ ! "$OWNER_NPUB" =~ ^npub1[a-z0-9]{58}$ ]]; then
    echo "Error: Invalid npub format. Must start with 'npub1' and be 63 characters long." >&2
    exit 1
fi

# Write config to persistent storage
echo "$CONFIG" > /data/config.yaml

# Extract values and write environment variables file
cat > /data/env.sh <<EOF
# Haven Environment Configuration
# Generated by Start9

export OWNER_NPUB="$OWNER_NPUB"
export DB_ENGINE="$(echo "$CONFIG" | yq '.db-engine // "badger"')"
export LMDB_MAPSIZE="$(echo "$CONFIG" | yq '.lmdb-mapsize // ""')"
export RELAY_VERSION="$(echo "$CONFIG" | yq '.relay-version // "1.0.6"')"

export PRIVATE_RELAY_NAME="$(echo "$CONFIG" | yq '.private-relay-name // "Haven Private"')"
export PRIVATE_RELAY_DESCRIPTION="$(echo "$CONFIG" | yq '.private-relay-description // "My private relay"')"

export CHAT_RELAY_NAME="$(echo "$CONFIG" | yq '.chat-relay-name // "Haven Chat"')"
export CHAT_RELAY_DESCRIPTION="$(echo "$CONFIG" | yq '.chat-relay-description // "My chat relay"')"
export CHAT_RELAY_WOT_DEPTH="$(echo "$CONFIG" | yq '.chat-wot-depth // "2"')"
export CHAT_RELAY_WOT_REFRESH_INTERVAL_HOURS="$(echo "$CONFIG" | yq '.chat-wot-refresh-interval // "24"')"
export CHAT_RELAY_MINIMUM_FOLLOWERS="$(echo "$CONFIG" | yq '.chat-minimum-followers // "10"')"

export OUTBOX_RELAY_NAME="$(echo "$CONFIG" | yq '.outbox-relay-name // "Haven Outbox"')"
export OUTBOX_RELAY_DESCRIPTION="$(echo "$CONFIG" | yq '.outbox-relay-description // "My outbox relay"')"

export INBOX_RELAY_NAME="$(echo "$CONFIG" | yq '.inbox-relay-name // "Haven Inbox"')"
export INBOX_RELAY_DESCRIPTION="$(echo "$CONFIG" | yq '.inbox-relay-description // "My inbox relay"')"
export INBOX_PULL_INTERVAL_SECONDS="$(echo "$CONFIG" | yq '.inbox-pull-interval // "3600"')"

export IMPORT_START_DATE="$(echo "$CONFIG" | yq '.import-start-date // ""')"
export BACKUP_PROVIDER="$(echo "$CONFIG" | yq '.backup-provider // "none"')"
export BACKUP_INTERVAL_HOURS="$(echo "$CONFIG" | yq '.backup-interval // "24"')"
export LOG_LEVEL="$(echo "$CONFIG" | yq '.log-level // "INFO"')"

# Import seed relays (convert comma-separated string to JSON array)
IMPORT_RELAYS="$(echo "$CONFIG" | yq '.import-seed-relays // ""')"
if [ ! -z "$IMPORT_RELAYS" ]; then
    echo "$IMPORT_RELAYS" | tr ',' '\n' | jq -R . | jq -s . > /data/relays_import.json
fi
EOF

# Make environment file readable
chmod 644 /data/env.sh

echo "Configuration updated successfully" >&2
exit 0

